name: Deployment to Staging
on:
  workflow_dispatch:
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

env:
  BUILD_DIR: ./build
jobs:
  build-staging:
    name: Build Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: yarn
          
      - name: Generate Algolia vars - staging
        if: github.ref == 'refs/heads/dev'
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: .github/templates/.env.staging.j2
          output_file: algolia.env
        env:
          ALGOLIA_APP_ID: ${{ vars.ALGOLIA_APP_ID }}
          ALGOLIA_INDEX_NAME: ${{ vars.ALGOLIA_INDEX_NAME }}
          ALGOLIA_API_KEY: ${{ vars.ALGOLIA_API_KEY }}

      - name: Install dependencies
        run: yarn install 

      - name: Test build website
        run: yarn build-staging
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gh-pages-depl-payload
          path: ./build

  deploy:
    name: Deploy to GitHub Pages
    needs: build-staging
    runs-on: ubuntu-latest
    steps:
     - uses: actions/download-artifact@master
       with:
         name: gh-pages-depl-payload
         path: ./build

     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./build

     - name: Wait some time to make sure deployment is finished
       run: |
         sleep 60
